trigger:
  branches:
    include:
    - main
  tags:
    include:
    - '*'
pr:
  branches:
    include:
    - main

jobs:
- job:
  displayName: linux
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      python3.9:
        python.version: '3.9'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: |
      set -e
      eval "$(conda shell.bash hook)"
      conda config --add channels conda-forge
      conda config --set channel_priority strict
      conda install --yes python=$PYTHON_VERSION conda conda-build mamba boa
      # workaround based on recent failures
      rm /usr/share/miniconda/pkgs/cache/*.json
      mamba update --all --yes
    displayName: Update conda base environment

  - bash: |
      eval "$(conda shell.bash hook)"
      # workaround based on recent failures
      rm /usr/share/miniconda/pkgs/cache/*.json
      conda mambabuild conda/
    displayName: Build mache metapackage
