{% set name = "mache" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=60
  run:
    - python >=3.10
    - importlib_resources
    - jinja2
    - lxml
    - packaging
    - pyyaml
    - requests
    - rsync
    - termcolor
    - tqdm

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
  imports:
    - mache
  commands:
    - mache sync diags --help
    - pip check
    - pytest tests

about:
  home: https://github.com/E3SM-Project/mache
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A package for providing configuration data relate to E3SM supported machines
  doc_url: https://github.com/E3SM-Project/mache/README.rst
  dev_url: https://github.com/E3SM-Project/mache

extra:
  recipe-maintainers:
    - xylar
